version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  processor:
    build:
      context: .
      target: processor
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DEBUG=hydra-processor:*
    command: sh -c "npm run db:migrate && npm run processor:migrate && npm run processor:start"

  query-node:
    restart: unless-stopped
    build:
      context: .
      target: query-node
    depends_on:
      - db
      - processor
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "4000:${GRAPHQL_SERVER_PORT}"
